#page title
page_title                                : Monza - Battle Royale                     # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : #1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : #                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/monza_icon.svg                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Monza 'Battle Royale'                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Monza 'Battle Royale' - The ultimate addon ruleset for Haba's Monza.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Cambragol                                
your_link                                 :                     
your_city                                 : An Unknown City                                
email_address                             : griffon_academy@yahoo.ca
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Chitty Chitty Bang Bang
    description                           : The Famous Flying Car! It can fly over Obstacle squares (tires) and land on the opposite side for two free movements!
    fontawesome_icon_name                 : magic
    
  - title                                 : The Great Leslie
    description                           : The Great Racer! He can reroll any 2 dice if not used.
    fontawesome_icon_name                 : mobile

  - title                                 : Professor Fate
    description                           : The Other Great Racer! Can move all players back one space, once per turn.
    fontawesome_icon_name                 : play-circle

  - title                                 : Herbie
    description                           : The Love Bug! Can move sideways once per turn.
    fontawesome_icon_name                 : sync

  - title                                 : James Bond
    description                           : 007. If he rolls 3 dice of the same color, he can move 3 free spaces at the end of his turn. The three dice cannot be used otherwise.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Thorndyke
    description                           : Herbies Nemesis! Can switch places with anyone, except first place.
    fontawesome_icon_name                 : star

  - title                                 : Marty's Delorean
    description                           : The Time Travelling Car! When passing through 2 of the same color spaces, can teleport to the next, third one.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : The Mystery Machine
    description                           : Scooby Dooby Doo! The last space color landed on becomes a trap, and all other players on that color are moved back two spaces.
    fontawesome_icon_name                 : shuttle-van

  - title                                 : Wheels on Meals
    description                           : Jackie's Foodtruck! Every car it goes directly behind, or in front of, is moved back one space
    fontawesome_icon_name                 : truck

  - title                                 : Agent Hawk's Mitsubishi
    description                           : It has a mini-bike inside! If it lands behind another player, he moves ahead 3 spaces.
    fontawesome_icon_name                 : star


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : monza                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
